name: Bug Report
description: Unexpected non-crash behaviour (except missing gameplay features)
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  attributes:
    label: Expected behavior
    description: What were you expecting to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual result
    description: What actually happened?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: Steps to reproduce the issue.
    placeholder: |
      1. ...
      2. ...
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ### OS and Environnement
- type: input
  attributes:
    label: PocketMine-MP version
  validations:
    required: true
- type: input
  attributes:
    label: PHP version
  validations:
    required: true
- type: dropdown
  attributes:
    label: Using JIT
    description: Look for the giant yellow warning in the log that says you're using JIT
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: input
  attributes:
    label: Server OS
  validations:
    required: true
- type: input
  attributes:
    label: Game version
    description: Android/iOS/Win10/Xbox/PS4/Switch
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Plugins
    description: If you remove all plugins, does the issue still occur?
    options:
      - label: "I can reproduce this issue without any plugins loaded"
        required: true
